<?php

return [
    'content_block_groups' => [
        'home_slide' => 'Accueil - diaporama',
        'home_card' => 'Accueil - cartes formations et appels',
        'home_service' => 'Accueil - blocs institutionnels',
        'institution_block' => 'Institution - presentation',
        'institution_service' => 'Institution - services et directions',
        'service_page' => 'Institution - pages services',
        'admission_intro' => 'Inscriptions - conditions et documents',
        'admission_step' => 'Inscriptions - etapes',
        'media_gallery' => 'Medias - galerie',
        'research_society' => 'Recherche et societe',
        'student_life' => 'Vie etudiante',
        'site_footer' => 'Pied de page',
        'quick_link' => 'Liens rapides',
    ],

    'publication_type_groups' => [
        'Scolarite et archives' => [
            'Document',
            'Bulletin Licence',
            'Bulletin Master',
            'Echeancier',
            'Frais',
            'Diplome',
            'Ressource',
            'Bibliotheque',
        ],
        'Recherche et societe' => [
            'Article',
            'Article scientifique',
            'These',
            'Formation enseignant',
            'Conference',
            'Seminaire',
            'Centre de recherche',
            'Projet',
            'Recherche',
            'Hackathon',
            'Realisation etudiant',
            'Travail Licence',
            'Travail Master',
            'Travail etudiant',
            'Travail enseignant',
            'Stage academique',
        ],
        'Vie etudiante et opportunites' => [
            'Opportunite',
            'Offre',
            'Emploi',
            'Stage',
            'Alumni',
        ],
        'Communication institutionnelle' => [
            'Communique',
            'Actualite',
            'In memoriam',
        ],
    ],

    'document_types' => [
        'Document',
        'Bulletin Licence',
        'Bulletin Master',
        'Echeancier',
        'Ressource',
        'Bibliotheque',
    ],

    'research_types' => [
        'Article',
        'Article scientifique',
        'These',
        'Formation enseignant',
        'Conference',
        'Seminaire',
        'Centre de recherche',
        'Projet',
        'Recherche',
        'Hackathon',
        'Realisation etudiant',
        'Travail Licence',
        'Travail Master',
        'Travail etudiant',
        'Travail enseignant',
        'Stage academique',
    ],

    'opportunity_types' => [
        'Opportunite',
        'Offre',
        'Emploi',
        'Stage',
    ],

    'admin_nav' => [
        [
            'label' => 'Pilotage',
            'items' => [
                ['label' => 'Tableau de bord ISC', 'route' => 'admin.dashboard', 'active' => 'admin.dashboard'],
                ['label' => 'Parametres institution', 'route' => 'admin.settings.index', 'active' => 'admin.settings.*'],
                ['label' => 'Navigation du site', 'route' => 'admin.menu-items.index', 'active' => 'admin.menu-items.*'],
            ],
        ],
        [
            'label' => 'Structure du site',
            'items' => [
                ['label' => 'Pages du site', 'route' => 'admin.pages.index', 'active' => 'admin.pages.*'],
                ['label' => 'Bannieres accueil', 'route' => 'admin.banners.index', 'active' => 'admin.banners.*'],
                ['label' => 'Cartes accueil', 'route' => 'admin.content-blocks.index', 'params' => ['group' => 'home_card'], 'active' => 'admin.content-blocks.*', 'query' => ['group' => ['home_card']]],
                ['label' => 'Institution et blocs', 'route' => 'admin.content-blocks.index', 'params' => ['group' => 'institution_service'], 'active' => 'admin.content-blocks.*', 'query' => ['group' => ['institution_block', 'institution_service', 'home_service', 'service_page']]],
                ['label' => 'Formations et filieres', 'route' => 'admin.sections.index', 'active' => 'admin.sections.*'],
                ['label' => 'Enseignants', 'route' => 'admin.staff.index', 'active' => 'admin.staff.*'],
                ['label' => 'Medias et galerie', 'route' => 'admin.media.index', 'active' => 'admin.media.*'],
            ],
        ],
        [
            'label' => 'Publications du site',
            'items' => [
                ['label' => 'Actualites / blog', 'route' => 'admin.news.index', 'active' => 'admin.news.*'],
                ['label' => 'Documents', 'route' => 'admin.publications.index', 'params' => ['type' => 'Document'], 'active' => 'admin.publications.*', 'query' => ['type' => ['Document', 'Bulletin Licence', 'Bulletin Master', 'Echeancier', 'Ressource', 'Bibliotheque']]],
                ['label' => 'Nos frais', 'route' => 'admin.publications.index', 'params' => ['type' => 'Frais'], 'active' => 'admin.publications.*', 'query' => ['type' => 'Frais']],
                ['label' => 'Palmares et diplomes', 'route' => 'admin.graduations.index', 'active' => 'admin.graduations.*'],
                ['label' => 'Recherche et societe', 'route' => 'admin.publications.index', 'params' => ['type' => 'Article scientifique'], 'active' => 'admin.publications.*', 'query' => ['type' => ['Article', 'Article scientifique', 'These', 'Formation enseignant', 'Conference', 'Seminaire', 'Centre de recherche', 'Projet', 'Recherche', 'Hackathon', 'Realisation etudiant', 'Travail Licence', 'Travail Master', 'Travail etudiant', 'Travail enseignant', 'Stage academique']]],
                ['label' => 'Opportunites et offres', 'route' => 'admin.publications.index', 'params' => ['type' => 'Opportunite'], 'active' => 'admin.publications.*', 'query' => ['type' => ['Opportunite', 'Offre', 'Emploi', 'Stage']]],
                ['label' => 'Alumni', 'route' => 'admin.publications.index', 'params' => ['type' => 'Alumni'], 'active' => 'admin.publications.*', 'query' => ['type' => 'Alumni']],
                ['label' => 'Evenements', 'route' => 'admin.events.index', 'active' => 'admin.events.*'],
            ],
        ],
        [
            'label' => 'Inscriptions et contact',
            'items' => [
                ['label' => 'Demandes inscription', 'route' => 'admin.admissions.index', 'active' => 'admin.admissions.*'],
                ['label' => 'Registre inscriptions', 'route' => 'admin.registry.index', 'active' => 'admin.registry.*'],
                ['label' => 'Paiements etudiants', 'route' => 'admin.student-payments.index', 'active' => 'admin.student-payments.*'],
                ['label' => 'Documents etudiants', 'route' => 'admin.student-documents.index', 'active' => 'admin.student-documents.*'],
                ['label' => 'Notifications etudiants', 'route' => 'admin.student-notifications.index', 'active' => 'admin.student-notifications.*'],
                ['label' => 'Messages', 'route' => 'admin.messages.index', 'active' => 'admin.messages.*'],
                ['label' => 'Commentaires etudiants', 'route' => 'admin.student-comments.index', 'active' => 'admin.student-comments.*'],
                ['label' => 'Production', 'route' => 'admin.production.index', 'active' => 'admin.production.*'],
            ],
        ],
    ],

    'site_modules' => [
        [
            'label' => 'Accueil',
            'description' => 'Diaporama, cartes de formation, blocs d appel et liens principaux de la page d accueil.',
            'public_url' => '/index.html',
            'actions' => [
                ['label' => 'Diaporama', 'route' => 'admin.banners.index'],
                ['label' => 'Cartes accueil', 'route' => 'admin.content-blocks.index', 'params' => ['group' => 'home_card']],
                ['label' => 'Actualites', 'route' => 'admin.news.index'],
            ],
        ],
        [
            'label' => 'Institution',
            'description' => 'A propos, services, directions, bourse, blocs vides a publier depuis le backend.',
            'public_url' => '/aboutus.html',
            'actions' => [
                ['label' => 'Pages institution', 'route' => 'admin.pages.index'],
                ['label' => 'Blocs institution', 'route' => 'admin.content-blocks.index', 'params' => ['group' => 'institution_service']],
                ['label' => 'Navigation', 'route' => 'admin.menu-items.index'],
            ],
        ],
        [
            'label' => 'Formation',
            'description' => 'Licence LMD, Master LMD, centre de formation, Cisco Academie, sections et filieres.',
            'public_url' => '/formation/licence.html',
            'actions' => [
                ['label' => 'Sections et filieres', 'route' => 'admin.sections.index'],
                ['label' => 'Enseignants', 'route' => 'admin.staff.index'],
            ],
        ],
        [
            'label' => 'Inscriptions',
            'description' => 'Conditions, bulletins, compte candidat, demandes et registre officiel.',
            'public_url' => '/inscription.html',
            'actions' => [
                ['label' => 'Demandes', 'route' => 'admin.admissions.index'],
                ['label' => 'Registre', 'route' => 'admin.registry.index'],
                ['label' => 'Paiements', 'route' => 'admin.student-payments.index'],
                ['label' => 'Documents inscription', 'route' => 'admin.publications.index', 'params' => ['type' => 'Bulletin Licence']],
            ],
        ],
        [
            'label' => 'Scolarite et archives',
            'description' => 'Documents publics, nos frais, nos diplomes et nos palmares.',
            'public_url' => '/documents.html',
            'actions' => [
                ['label' => 'Documents', 'route' => 'admin.publications.index', 'params' => ['type' => 'Document']],
                ['label' => 'Frais', 'route' => 'admin.publications.index', 'params' => ['type' => 'Frais']],
                ['label' => 'Palmares', 'route' => 'admin.graduations.index'],
            ],
        ],
        [
            'label' => 'Recherche et societe',
            'description' => 'Travaux des etudiants, publications enseignants, stages, conferences, projets et hackathon.',
            'public_url' => '/services-a-la-societe.html',
            'actions' => [
                ['label' => 'Publier recherche', 'route' => 'admin.publications.index', 'params' => ['type' => 'Article scientifique']],
                ['label' => 'Evenements', 'route' => 'admin.events.index'],
            ],
        ],
        [
            'label' => 'Vie etudiante',
            'description' => 'Nouveaux etudiants, college des etudiants, alumni, opportunites et connexion etudiant.',
            'public_url' => '/page/new-isigien.html',
            'actions' => [
                ['label' => 'Opportunites', 'route' => 'admin.publications.index', 'params' => ['type' => 'Opportunite']],
                ['label' => 'Alumni', 'route' => 'admin.publications.index', 'params' => ['type' => 'Alumni']],
                ['label' => 'Documents etudiants', 'route' => 'admin.student-documents.index'],
                ['label' => 'Commentaires', 'route' => 'admin.student-comments.index'],
            ],
        ],
        [
            'label' => 'Medias et contact',
            'description' => 'Galerie, media-center, blog, messages et informations de contact.',
            'public_url' => '/media-center.html',
            'actions' => [
                ['label' => 'Galerie', 'route' => 'admin.media.index'],
                ['label' => 'Blog', 'route' => 'admin.news.index'],
                ['label' => 'Messages', 'route' => 'admin.messages.index'],
            ],
        ],
    ],

    'menu' => [
        'parents' => [
            ['Accueil', '/index.html', 1],
            ['Institution', '/aboutus.html', 2],
            ['Formation', '/index.html#formations', 3],
            ['Vie etudiante', '/page/new-isigien.html', 4],
            ['Recherche et societe', '/services-a-la-societe.html', 5],
            ['Contact', '/contact.html', 6],
        ],
        'children' => [
            'Institution' => [
                ['Decouvrir l ISC-KINDU', '/aboutus.html#apropos', 1],
                ['Nos services', '/services.html', 2],
                ['Bourse ISC Kindu', '/bourse-isc-kindu.html', 3],
                ['Travailler a l ISC Kindu', '/travailler-a-isc/offres.html', 4],
                ['Galerie', '/media-center.html', 5],
                ['Blog', '/blog.html', 6],
            ],
            'Formation' => [
                ['Licence LMD', '/formation/licence.html', 1],
                ['Master LMD', '/formation/master.html', 2],
                ['Centre de Formation', '/formation/centre-de-formation.html', 3],
                ['Cisco Academie', '/formation/cisco-academie.html', 4],
                ['Nos enseignants', '/nos-enseignants.html', 5],
                ['Inscription', '/inscription.html', 6],
                ['Scolarite et archives', '/documents.html', 7],
                ['Nos diplomes', '/nos-diplomes.html', 8],
                ['Nos palmares', '/nos-palmares.html', 9],
                ['Nos frais', '/nos-frais.html', 10],
            ],
            'Vie etudiante' => [
                ['Bienvenue aux nouveaux', '/page/new-isigien.html', 1],
                ['College des etudiants', '/page/college.html', 2],
                ['Nos alumni', '/page/alumni.html', 3],
                ['Opportunites', '/travailler-a-isc/opportunites.html', 4],
                ['Nos offres d emploi', '/travailler-a-isc/offres.html', 5],
                ['Connexion etudiant', '/login.html', 6],
            ],
            'Recherche et societe' => [
                ['Travaux de Licence', '/recherche-societe/travaux-licence.html', 1],
                ['Travaux de Master', '/recherche-societe/travaux-master.html', 2],
                ['Stage academique', '/recherche-societe/stage-academique.html', 3],
                ['Publications enseignants', '/recherche-societe/publications-enseignants.html', 4],
                ['Formations et theses', '/recherche-societe/formation-enseignants.html', 5],
                ['Conferences et seminaires', '/recherche-societe/seminaires-conferences.html', 6],
                ['Nos projets', '/recherche-societe/nos-projets.html', 7],
                ['Hackathon', '/recherche-societe/hackathon.html', 8],
                ['Realisations', '/recherche-societe/realisations.html', 9],
            ],
        ],
        'flat' => [
            ['topbar', 'S inscrire a l ISC Kindu', '/inscription.html', 1],
            ['topbar', 'Connexion etudiant', '/login.html', 2],
            ['topbar', 'Nos frais', '/nos-frais.html', 3],
            ['footer', 'Nos documents', '/documents.html', 1],
            ['footer', 'Nos frais', '/nos-frais.html', 2],
            ['footer', 'Contactez-nous', '/contact.html', 3],
        ],
    ],

    'pages' => [
        ['Accueil', 'accueil', 'Page d accueil institutionnelle ISC KINDU.', '/images/site/photo-1.jpg', '/index.html'],
        ['Institution', 'institution', 'Presentation de l ISC KINDU et de son organisation.', '/images/site/photo-2.jpg', '/aboutus.html'],
        ['Nos services', 'services', 'Directions, services et blocs institutionnels a publier depuis le backend.', '/images/site/photo-3.jpg', '/services.html'],
        ['Bourse ISC Kindu', 'bourse-isc-kindu', 'Informations de bourse a completer depuis le backend.', '/images/site/photo-4.jpg', '/bourse-isc-kindu.html'],
        ['Formation', 'formation', 'Vue generale des formations organisees.', '/images/site/photo-5.jpg', '/formation/licence.html'],
        ['Licence LMD', 'licence', 'Programmes de licence organises a l ISC KINDU.', '/images/site/photo-6.jpg', '/formation/licence.html'],
        ['Master LMD', 'master', 'Programmes de master a publier si disponibles.', '/images/site/photo-7.jpg', '/formation/master.html'],
        ['Centre de Formation', 'centre-de-formation', 'Formation continue et renforcement des capacites.', '/images/site/photo-8.jpg', '/formation/centre-de-formation.html'],
        ['Cisco Academie', 'cisco-academie', 'Parcours Cisco Academie.', '/images/site/photo-9.jpg', '/formation/cisco-academie.html'],
        ['Inscription', 'inscription', 'Parcours candidat et inscription en ligne.', '/images/site/photo-8.jpg', '/inscription.html'],
        ['Documents', 'documents', 'Documents et ressources publies depuis l administration.', '/images/site/photo-9.jpg', '/documents.html'],
        ['Nos diplomes', 'diplomes', 'Diplomes et documents academiques publics.', '/images/site/photo-4.jpg', '/nos-diplomes.html'],
        ['Nos palmares', 'palmares', 'Palmares et listes de diplomes publies depuis le backend.', '/images/site/photo-5.jpg', '/nos-palmares.html'],
        ['Nos frais', 'frais', 'Fichiers des frais a publier depuis le backend.', '/images/site/photo-6.jpg', '/nos-frais.html'],
        ['Medias', 'medias', 'Galerie photo, video et media-center.', '/images/site/photo-7.jpg', '/media-center.html'],
        ['Blog', 'blog', 'Actualites et annonces publiees depuis le backend.', '/images/site/photo-8.jpg', '/blog.html'],
        ['Nos enseignants', 'enseignants', 'Liste des enseignants et membres actifs.', '/images/site/photo-9.jpg', '/nos-enseignants.html'],
        ['Vie etudiante', 'vie-etudiante', 'Pages utiles aux nouveaux etudiants.', '/images/site/photo-1.jpg', '/page/new-isigien.html'],
        ['Bienvenue aux nouveaux', 'nouveau-etudiant', 'Accueil des nouveaux etudiants.', '/images/site/photo-2.jpg', '/page/new-isigien.html'],
        ['College des etudiants', 'college', 'Informations du college des etudiants.', '/images/site/photo-2.jpg', '/page/college.html'],
        ['Alumni', 'alumni', 'Espace communautaire des anciens etudiants.', '/images/site/photo-3.jpg', '/page/alumni.html'],
        ['Opportunites', 'opportunites', 'Offres, stages et opportunites publies depuis le backend.', '/images/site/photo-4.jpg', '/travailler-a-isc/opportunites.html'],
        ['Nos offres d emploi', 'offres-emploi', 'Offres d emploi publiees par l ISC Kindu et ses partenaires.', '/images/site/photo-4.jpg', '/travailler-a-isc/offres.html'],
        ['Recherche et societe', 'recherche-societe', 'Travaux, projets, realisations et publications.', '/images/site/photo-5.jpg', '/services-a-la-societe.html'],
        ['Travaux de licence', 'travaux-licence', 'Travaux de licence a publier depuis le backend.', '/images/site/photo-6.jpg', '/recherche-societe/travaux-licence.html'],
        ['Travaux de master', 'travaux-master', 'Travaux de master a publier depuis le backend.', '/images/site/photo-7.jpg', '/recherche-societe/travaux-master.html'],
        ['Stage academique', 'stage-academique', 'Stages academiques et encadrements.', '/images/site/photo-7.jpg', '/recherche-societe/stage-academique.html'],
        ['Publications enseignants', 'publications-enseignants', 'Articles scientifiques et publications.', '/images/site/photo-8.jpg', '/recherche-societe/publications-enseignants.html'],
        ['Formations et theses', 'formation-enseignants', 'Formations, theses et parcours enseignants.', '/images/site/photo-8.jpg', '/recherche-societe/formation-enseignants.html'],
        ['Conferences et seminaires', 'seminaires-conferences', 'Conferences, seminaires et rencontres scientifiques.', '/images/site/photo-8.jpg', '/recherche-societe/seminaires-conferences.html'],
        ['Nos projets', 'nos-projets', 'Projets academiques et services a la societe.', '/images/site/photo-8.jpg', '/recherche-societe/nos-projets.html'],
        ['Hackathon', 'hackathon', 'Hackathons et initiatives numeriques.', '/images/site/photo-8.jpg', '/recherche-societe/hackathon.html'],
        ['Realisations', 'realisations', 'Realisations des etudiants et de la communaute.', '/images/site/photo-8.jpg', '/recherche-societe/realisations.html'],
        ['Contact', 'contact', 'Coordonnees et formulaire de contact.', '/images/site/photo-9.jpg', '/contact.html'],
        ['Politique de confidentialite', 'politique-de-confidentialite', 'Texte legal a completer.', '/images/site/photo-1.jpg', '/politique-de-confidentialite.html'],
        ['Cookies', 'cookies', 'Politique cookies a completer.', '/images/site/photo-2.jpg', '/cookies.html'],
    ],

    'academic_structure' => [
        [
            'name' => 'Sciences Economiques et de Gestion',
            'slug' => 'sciences-economiques-et-de-gestion',
            'description' => 'Filiere de gestion, commerce, comptabilite, fiscalite, marketing et management.',
            'programs' => [
                ['Marketing', 'lm-marketing', 'Licence', 'Marketing et gestion commerciale.'],
                ['Fiscalite, Douane et Accises', 'lfda-fiscalite-douane-et-accises', 'Licence', 'Fiscalite, douane et accises.'],
                ['Informatique Appliquee a la Gestion', 'liage-informatique-appliquee-a-la-gestion-des-entreprises', 'Licence', 'Informatique appliquee aux organisations.'],
                ['Comptabilite et Finance', 'lcf-comptabilite-et-finance', 'Licence', 'Comptabilite, finance et controle.'],
                ['Comptabilite, Controle et Audit', 'mcca-comptabilite-controle-et-audit', 'Master', 'Audit, controle et pilotage financier.'],
                ['Marketing', 'mm-marketing', 'Master', 'Marketing strategique et operationnel.'],
                ['Fiscalite', 'mf-fiscalite', 'Master', 'Fiscalite appliquee.'],
                ['Douanes, Accises et Commerce International', 'mdaci-douanes-accises-et-commerce-international', 'Master', 'Douanes, accises et commerce international.'],
                ['Ingenierie et Management des Systemes d Information', 'miage-imsi-ingenierie-et-management-des-systemes-dinformation', 'Master', 'Management des systemes d information.'],
            ],
        ],
        [
            'name' => 'Sciences et Technologies',
            'slug' => 'sciences-et-technologies',
            'description' => 'Filiere informatique, reseaux, intelligence artificielle et genie logiciel.',
            'programs' => [
                ['Systemes Informatiques', 'lsi-systemes-informatiques', 'Licence', 'Systemes informatiques.'],
                ['Intelligence Artificielle', 'lsi-ia-intelligence-artificielle', 'Licence', 'Intelligence artificielle.'],
                ['Genie Logiciel', 'lsi-gl-genie-logiciel', 'Licence', 'Genie logiciel.'],
                ['Reseau et Telecommunication', 'rtel', 'Licence', 'Reseaux et telecommunications.'],
                ['Ingenierie en Reseaux Informatiques et Telecommunications', 'mirtl-ingenierie-en-reseaux-informatiques-et-telecommunications', 'Master', 'Ingenierie reseaux et telecommunications.'],
                ['Intelligence Artificielle', 'mia-intelligence-artificielle', 'Master', 'Intelligence artificielle avancee.'],
                ['Ingenierie Logiciel', 'mil-ingenierie-logiciel', 'Master', 'Ingenierie logicielle.'],
            ],
        ],
    ],

    'institution_service_blocks' => [
        ['institution_service.dg', 'Direction Generale', '/service/dg.html', 1],
        ['institution_service.academique', 'Secretariat General Academique', '/service/academique.html', 2],
        ['institution_service.admin_fin', 'Secretariat General Administratif et Financier', '/service/admin-fin.html', 3],
        ['institution_service.dsig', 'Direction des Systemes d Informations', '/service/dsig.html', 4],
        ['institution_service.section', 'Chef de Section', '/service/section.html', 5],
        ['institution_service.recherche', 'Recherche academique et Innovation', '/service/recherche-academique.html', 6],
        ['institution_service.apparitorat', 'Apparitorat', '/service/apparitorat.html', 7],
        ['institution_service.bibliotheque', 'Bibliotheque', '/service/bibliotheque.html', 8],
        ['institution_service.cfpi', 'Centre de Formation Professionnelle', '/service/cfpi.html', 9],
        ['institution_service.comptabilite', 'Comptabilite et Finance', '/service/comptabilite.html', 10],
        ['institution_service.laboinfo', 'Laboratoire informatique et reseaux', '/service/laboinfo.html', 11],
    ],
];
